version: "3.9"
services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_DB: "postgres_db"
      POSTGRES_USER: "truedi1905"
      POSTGRES_PASSWORD: "chelsea1905"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: truedi1905/sticker_bot:v1.1
    #build: .
    restart: always
    depends_on:
      - db
